Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-1, pull requests merged in 2025-02, with the labels that each got.

#40 Id1 code freeze spike url reader, re-throwing errors
  projectApp/src/components/LocalCSVReader.tsx
Labels: documentation

#43 Id1 code freeze spike logging completed, updated unit testing with logs
  .gitignore
  projectApp/package-lock.json
  projectApp/package.json
  projectApp/src/README.md
  projectApp/src/components/LocalCSVReader.tsx
  projectApp/src/components/UrlCSVReader.tsx
  projectApp/src/logging/README.md
  projectApp/src/logging/elastic.js
  projectApp/src/logging/logs.js
  projectApp/test/README.md
  projectApp/test/csvTesting.tsx
  projectApp/tsconfig.app.json
  projectApp/tsconfig.node.json
Labels: documentation

#44 Id1 code freeze spike, merging to update and logging
  .gitignore
  projectApp/package-lock.json
  projectApp/package.json
  projectApp/src/README.md
  projectApp/src/components/LocalCSVReader.tsx
  projectApp/src/components/UrlCSVReader.tsx
  projectApp/src/data_structures/CSVHeaders.tsx
  projectApp/src/data_structures/TimeSeriesData.tsx
  projectApp/src/logging/README.md
  projectApp/src/logging/elastic.js
  projectApp/src/logging/logs.js
  projectApp/test/README.md
  projectApp/test/csvTesting.tsx
  projectApp/tsconfig.app.json
  projectApp/tsconfig.node.json
Labels: documentation

#70 Id2 dev prep -> dev branch
  projectApp/package-lock.json
  projectApp/src/components/CSV_Readers/LocalCSVReader.tsx
  projectApp/src/components/CSV_Readers/UrlCSVReader.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/components/Graph_Components/PointClass.tsx
  projectApp/src/pages/Graph_Objects/Point2D.tsx
  projectApp/src/pages/Graph_Objects/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/types/CSVInterfaces.tsx
  projectApp/src/types/GraphInterface.tsx
  projectApp/src/types/PointInterface.tsx
  projectApp/test/csvTesting.tsx
Labels: good first issue

#81 Id2 dev ui and refactor; making a pull request to add linter to ID2Dev branch
  projectApp/eslint.config.js
  projectApp/package-lock.json
  projectApp/package.json
  projectApp/src/App.tsx
  projectApp/src/components/CSV_Readers/LocalCSVReader.tsx
  projectApp/src/components/CSV_Readers/UrlCSVReader.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/logging/elastic.js
  projectApp/src/models/CSVDataModel.tsx
  projectApp/src/models/CSVReaderModel.tsx
  projectApp/src/pages/Graph_Objects/Point2D.tsx
  projectApp/src/types/CSVInterfaces.tsx
  projectApp/test/csvTesting.tsx
Labels: enhancement

#109 Id2 dev ui and refactor branch to ID2Dev branch
  projectApp/eslint.config.js
  projectApp/package-lock.json
  projectApp/src/App.tsx
  projectApp/src/components/CSV_Readers/LocalCSVReader.tsx
  projectApp/src/components/CSV_Readers/UrlCSVReader.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/models/CSVDataModel.tsx
  projectApp/src/models/CSVDataObject.tsx
  projectApp/src/models/CSVReaderModel.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
  projectApp/src/pages/UI/DropdownUI.tsx
  projectApp/src/types/BaseInterfaces.tsx
  projectApp/src/types/CSVInterfaces.tsx
  projectApp/test/CSVController.test.ts
  projectApp/test/MainController.test.ts
  projectApp/test/csvModelTest.tsx
  projectApp/test/csvTesting.tsx
Labels: enhancement

#114 Refactoring and code restructuring for Graph Interface, Graph Class and creation of interface for GraphClass2
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/components/Graph_Components/GraphClass.test.ts
  projectApp/src/components/Graph_Components/GraphClass.tsx
  projectApp/src/models/CSVDataObject.tsx
  projectApp/src/types/GraphClass2Interface.tsx
  projectApp/src/types/GraphInterface.tsx
Labels: enhancement

#119 Id2 dev create time series integration
  .github/workflows/BuildandTest.yml
  csvTestFiles/test.csv
  projectApp/.gitignore
  projectApp/eslint.config.js
  projectApp/src/App.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/components/Graph_Components/GraphClass.test.ts
  projectApp/src/components/Graph_Components/GraphClass.tsx
  projectApp/src/components/Graph_Components/GraphClass2.test.ts
  projectApp/src/components/Graph_Components/GraphClass2.tsx
  projectApp/src/components/Graph_Components/PointClass.tsx
  projectApp/src/components/Graph_Components/TimeSeriesGraphClass.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/models/CSVDataObject.tsx
  projectApp/src/models/CSVReaderModel.tsx
  projectApp/src/models/GraphModel.tsx
  projectApp/src/pages/Graph_Objects/Point2D.tsx
  projectApp/src/pages/Graph_Objects/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/UI/DropdownUI.tsx
  projectApp/src/types/BaseInterfaces.tsx
  projectApp/src/types/CSVInterfaces.tsx
  projectApp/src/types/EmbeddedInterface.tsx
  projectApp/src/types/GraphInterface.tsx
  projectApp/src/types/TimeSeriesGraphInterface.tsx
  projectApp/test/CSVController.test.ts
  projectApp/test/MainController.test.ts
  projectApp/test/TimeSeriesGraphClass.test.ts
Labels: enhancement

#143 ID2-Testing: Logger-Frontend commenting
  Tests/csvLoader.feature
  projectApp/src/logger-frontend.ts
Labels: documentation
