Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-1, pull requests merged in 2025-04, with the labels that each got.

#287 ID5-Features: DDInfoBox
  projectApp/src/pages/UI/DropdownUI.tsx
Labels: enhancement

#303 Defect #21 & #29 fix: Invalid CSV Files
  projectApp/src/components/Csv_Components/CSVDataObject.ts
  projectApp/src/components/Graph_Components/GraphObject.ts
  projectApp/src/controller/CSVController.ts
  projectApp/src/models/CSVReaderModel.ts
  projectApp/src/pages/UI/BrowserUI.tsx
  projectApp/src/types/BaseInterfaces.ts
  projectApp/src/types/CSVInterfaces.ts
  projectApp/src/types/GraphInterface.ts
  projectApp/tests/unit_tests/CSVController.test.ts
  projectApp/tests/unit_tests/GraphClass.test.ts
Labels: bug

#312 ID5-UnitTests-TimeSeriesGraphObject
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Labels: testing

#283 Id5 defects defect20
  csvTestFiles/negativeTest.csv
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.ts
  projectApp/src/controller/GraphController.ts
  projectApp/src/models/CSVReaderModel.ts
  projectApp/src/models/GraphModel.ts
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/UI/DropdownUI.tsx
  projectApp/tests/smoke_tests/graph.test.ts
  projectApp/tests/unit_tests/CSVController.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Labels: bug, potential risk

#314 Id5 defects
  csvTestFiles/negativeTest.csv
  projectApp/src/components/Csv_Components/CSVDataObject.ts
  projectApp/src/components/Graph_Components/GraphObject.ts
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.ts
  projectApp/src/controller/CSVController.ts
  projectApp/src/controller/GraphController.ts
  projectApp/src/models/CSVReaderModel.ts
  projectApp/src/models/GraphModel.ts
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
  projectApp/src/pages/UI/DropdownUI.tsx
  projectApp/src/types/CSVInterfaces.ts
  projectApp/tests/logConfirmationTests/2DGraph.test.ts
  projectApp/tests/logConfirmationTests/CSVLoaderLogs.test.ts
  projectApp/tests/logConfirmationTests/logConfirmationlogs.txt
  projectApp/tests/smoke_tests/graph.test.ts
  projectApp/tests/unit_tests/CSVController.test.ts
  projectApp/tests/unit_tests/GraphClass.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Labels: bug, potential risk

#323 Id5 log confirmation
  Tests/2DGraph.feature
  projectApp/tests/logConfirmationTests/2DGraph.test.ts
  projectApp/tests/logConfirmationTests/EmbeddedConfirmation.test.ts
Labels: testing

#326 Id5 f dif graph changes
  projectApp/src/components/Graph_Components/EmbeddedGraphObject.ts
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.ts
  projectApp/src/controller/GraphController.ts
Labels: bug

#329 ID5 - Interface Fixes
  projectApp/src/types/CSVInterfaces.ts
  projectApp/src/types/EmbeddedInterface.ts
  projectApp/src/types/GraphInterface.ts
  projectApp/src/types/TimeSeriesGraphInterface.ts
Labels: documentation

#325 Id5 unittests
  projectApp/package-lock.json
  projectApp/src/controller/CSVController.ts
  projectApp/src/controller/GraphController.ts
  projectApp/src/models/CSVReaderModel.ts
  projectApp/src/types/EmbeddedInterface.ts
  projectApp/tests/unit_tests/CSVController.test.ts
  projectApp/tests/unit_tests/CSVReaderModel.test.ts
  projectApp/tests/unit_tests/EmbeddedGraph.test.ts
  projectApp/tests/unit_tests/GraphController.test.ts
  projectApp/tests/unit_tests/PointObjects.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Labels: bug, help wanted, testing
