Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-1, pull requests merged in 2025-03, with the labels that each got.

#159 ID3-3DGraph-EmbeddedGraph
  projectApp/src/components/Graph_Components/CreateEmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
Labels: enhancement

#173 ID3-3DGraph-GraphController
  projectApp/src/controller/GraphController.tsx
Labels: enhancement

#183 Id3 test scene view
  projectApp/src/App.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/InitScene.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/Scene/TestScene.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
Labels: testing

#187 Id3 test scene
  projectApp/src/App.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/InitScene.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/Scene/TestScene.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
Labels: testing

#188 Id3 testing embedded log confirmation
  projectApp/tests/logConfirmationTests/EmbeddedConfirmation.test.ts
Labels: testing

#190 Id3 testing
  Tests/embedded_graph.feature
  projectApp/tests/logConfirmationTests/EmbeddedConfirmation.test.ts
Labels: testing

#221 Made program widescreen, also deleted extra BrowserUI component
  projectApp/src/App.tsx
Labels: enhancement

#232 ID4 Smoke Tests - Smoke Test Gherkin
  Tests/smokeTest.feature
Labels: enhancement, testing

#233 Id4 embedded graph vr points
  projectApp/src/components/Csv_Components/CSVDataObject.tsx
  projectApp/src/components/Csv_Components/CSVReaders.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx
  projectApp/src/components/Graph_Components/GraphObject.tsx
  projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Point2DObject.tsx
  projectApp/src/components/Graph_Components/Points/Point3DObject.tsx
  projectApp/src/components/Graph_Components/Points/PointObject.tsx
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/types/EmbeddedInterface.tsx
  projectApp/src/types/GraphInterface.tsx
  projectApp/src/types/GraphPointsInterfaces.ts
  projectApp/src/types/PointInterface.tsx
  projectApp/src/types/TimeSeriesGraphInterface.tsx
  projectApp/tests/unit_tests/EmbeddedGraph.test.ts
  projectApp/tests/unit_tests/GraphClass.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
  projectApp/tests/unit_tests/csvMockFS.test.ts
  projectApp/tests/unit_tests/csvTesting.test.ts
Labels: enhancement, help wanted

#234 Id4 embedded graph vr
  projectApp/src/components/Csv_Components/CSVDataObject.tsx
  projectApp/src/components/Csv_Components/CSVReaders.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx
  projectApp/src/components/Graph_Components/GraphObject.tsx
  projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Point2DObject.tsx
  projectApp/src/components/Graph_Components/Points/Point3DObject.tsx
  projectApp/src/components/Graph_Components/Points/PointObject.tsx
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/types/EmbeddedInterface.tsx
  projectApp/src/types/GraphInterface.tsx
  projectApp/src/types/GraphPointsInterfaces.ts
  projectApp/src/types/PointInterface.tsx
  projectApp/src/types/TimeSeriesGraphInterface.tsx
  projectApp/tests/unit_tests/EmbeddedGraph.test.ts
  projectApp/tests/unit_tests/GraphClass.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
  projectApp/tests/unit_tests/csvMockFS.test.ts
  projectApp/tests/unit_tests/csvTesting.test.ts
Labels: enhancement

#241 Id4 embedded graph link
  projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx
  projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
Labels: enhancement

#235 Id4 UI update
  projectApp/src/App.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/pages/Scene/InitScene.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/Scene/TestScene.tsx
  projectApp/src/pages/UI/DropdownUI.tsx
Labels: enhancement, help wanted

#244 Id4 bug fixes
  csvTestFiles/indexedRealFloatData.csv
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
Labels: help wanted, potential risk, testing

#243 Id4 embedded graph
  projectApp/package-lock.json
  projectApp/src/App.tsx
  projectApp/src/components/Csv_Components/CSVDataObject.tsx
  projectApp/src/components/Csv_Components/CSVReaders.tsx
  projectApp/src/components/Graph_Components/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/CreateEmbeddedGraph.tsx
  projectApp/src/components/Graph_Components/CreateTimeSeries.tsx
  projectApp/src/components/Graph_Components/EmbeddedGraphObject.tsx
  projectApp/src/components/Graph_Components/GraphObject.tsx
  projectApp/src/components/Graph_Components/Points/Create2DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Create3DPoint.tsx
  projectApp/src/components/Graph_Components/Points/Point2DObject.tsx
  projectApp/src/components/Graph_Components/Points/Point3DObject.tsx
  projectApp/src/components/Graph_Components/Points/PointObject.tsx
  projectApp/src/components/Graph_Components/TimeSeriesGraphObject.tsx
  projectApp/src/controller/CSVController.tsx
  projectApp/src/controller/GraphController.tsx
  projectApp/src/controller/MainController.tsx
  projectApp/src/models/CSVReaderModel.tsx
  projectApp/src/pages/Graph_Elements/EmbeddedGraph.tsx
  projectApp/src/pages/Graph_Elements/Point2D.tsx
  projectApp/src/pages/Graph_Elements/Point3D.tsx
  projectApp/src/pages/Graph_Elements/TimeSeriesGraph.tsx
  projectApp/src/pages/Scene/InitScene.tsx
  projectApp/src/pages/Scene/MainScene.tsx
  projectApp/src/pages/UI/BrowserUI.tsx
  projectApp/src/types/CSVInterfaces.tsx
  projectApp/src/types/EmbeddedInterface.tsx
  projectApp/src/types/GraphInterface.tsx
  projectApp/src/types/GraphPointsInterfaces.ts
  projectApp/src/types/PointInterface.tsx
  projectApp/src/types/TimeSeriesGraphInterface.tsx
  projectApp/tests/unit_tests/EmbeddedGraph.test.ts
  projectApp/tests/unit_tests/GraphClass.test.ts
  projectApp/tests/unit_tests/TimeSeriesGraphClass.test.ts
  projectApp/tests/unit_tests/csvMockFS.test.ts
  projectApp/tests/unit_tests/csvTesting.test.ts
Labels: enhancement, help wanted, testing

#246 ID4 Smoke Tests (Graph Tests)
  projectApp/tests/smoke_tests/graph.test.ts
  projectApp/tests/smoke_tests/graphLogConfirmation.test.ts
  projectApp/tests/smoke_tests/smokeTestLogs.txt
Labels: enhancement
